apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-sample-001-stage
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/quarkus-sample-001/overlays/stage
    repoURL: https://github.com/rhtap-skitamura-org/quarkus-sample-repo-001-gitops.git
    targetRevision: main
  destination:
    namespace: quarkus-sample-001-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

