apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus-sample-001
  janus-idp.io/tekton: quarkus-sample-001
  backstage.io/kubernetes-id: quarkus-sample-001
  backstage.io/kubernetes-namespace: quarkus-sample-001 
  app.kubernetes.io/part-of: quarkus-sample-001
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
