apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-sample-001
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-sample-001 
  name: quarkus-sample-001
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-sample-001
    weight: 100 
